version: '3.8'

services:
  # backend is a Java Spring Boot application java JDK 21 java 21 on debian-slim
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  # frontend is a React application in Vite (node latest lts: 22) on debian-slim
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    # volumes:
    #   - ./frontend:/app
    depends_on:
      - backend