# Identifiants du projet
sonar.projectKey=EcoTrip
sonar.projectName=EcoTrip

# Localisation des fichiers sources et de test
sonar.sources=src/main/java
sonar.tests=src/test/java


sonar.java.binaries=target/classes

# Rapports de tests JUnit générés par Surefire
sonar.junit.reportPaths=target/surefire-reports

# Rapport de couverture binaire généré par JaCoCo (exec)
sonar.jacoco.reportPaths=target/jacoco.exec

# Rapport XML JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/generated/**,**/config/**
